### PR TITLE
Adding a post about running docker commands on multiple items

### PR DESCRIPTION
**Pull request by urfolomeus**

### CODE REVIEW

**Review by munckymagik — APPROVED** [review]

**Comment by munckymagik** [comment]
It's good as is. Up to you but I had to add a slash to get this query to work:

```
$ docker images -q deliveroo/*
0a2931b0e3c6
9d4dcad25dd6
d5ec4932493b
0cc3c00ba467
b263e81e5e96
```

**Comment by spencer** [comment]
Looks great @urfolomeus 👍

**Comment by urfolomeus** [comment]
I had this same thing yesterday but only when the image name had a `/` in it. I checked the commands that are in the post in both Fish and Bash so I think that they should work?

**Comment by munckymagik** [comment]
Oh they do work yes. It's just `-q deliver*` doesn't match anything. It's not until I added the full `deliveroo/*`.

To be honest maybe just keep it simple. People can discover the nuances of it themselves. It is byte-sized after all, there's only so much you can fit into 8-bits.

**Pull request merged**
