### PR TITLE
Original size, but tweak font colour

### PR DESCRIPTION
**Pull request by paulanthonywilson**
Copied from main site; makes the body less harsh. That's what I think I meant by looking like it was running out of toner; gave it a not-anti-aliased sort-of look. Making the font bigger didn't help.

I checked our main site and copied the font colour which I think helps.

Also the author bit is more grey as I think it looks better that way

 ¯\(°_o)/¯☕️

### CODE REVIEW

**Comment by spencer** [comment]
Ahh. Just on the metadata! I see. I thought you meant on the body copy. Which wouldn't have affected the metadata much.

**Comment by paulanthonywilson** [comment]
Ok, so if this is acceptable I can merge this into your branch and then we can merge your branch into master, then we'd be ready to publicise ...

**Comment by paulanthonywilson** [comment]
(I don't understand the your metadata comment) :-/

**Comment by spencer** [comment]
Yeah. It's all good to meds afaict.

 I think it was the date you were finding spidery. I'd (wrongly) thought you'd meant the main copy. My fix was for that...and wouldn't have affected the date very much...Your fix looks good. 🙂

--
mobile: 07802 443407
email: hello@spencerturner.co.uk
skype: spencerturner twitter: @spencerturner

**Comment by paulanthonywilson** [comment]
No, it was all the text that looked spidery; fixed it by copying the text colour from the main Cultivate HQ site. The date and author bit is an afterthought.

**Pull request merged**
