### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by picandocodigo**
Some temporary branding.

image

### CODE REVIEW

**Comment by paulanthonywilson** [comment]
capto_capture 2019-01-03_05-32-21_pm

It's not working for me on blog posts.

**Comment by picandocodigo** [comment]
> capto_capture 2019-01-03_05-32-21_pm
> 
> It's not working for me on blog posts.

Fixed!

**Review by paulanthonywilson — APPROVED** [review]
Yay!

**Comment by paulanthonywilson** [comment]
Closing as @spencer is also adding a logo and other things in https://github.com/CultivateHQ/bytesize-blog/pull/9

**Pull request closed without merging**
